### ISSUE TITLE
Add strong name signatures

### ISSUE THREAD

**Issue by GieltjE** [jarzynam/continuous#3]
Without strong name signatures it is impossible to use them in a production environment where the main package has strong name signatures (it also ensures everyone can track wether or not it was you who pushed the new version).

It shouldn't be more than a few minutes of work, it doesn't break any other scenario. Just do not upload the key to github and keep a backup. (Strong name signatures are free to generate unlike code signing certificates).

**Comment by jarzynam** [comment]
Thanks @GieltjE this is a good idea. I am including this case to my development plan.

Is this issue an obstacle to use my library by you? If yes I will put high priority on this functionality.

**Comment by GieltjE** [comment]
For now I have combined all libraries into a single one, added it to our manual build chain and sign it with our own strong name signature. However that requires me to manually apply all patches.

If you could get it signed in (one of) the upcomming release that would be awesome (shouldn't really be more than a few minutes of work usually).

**Comment by jarzynam** [comment]
Ok, I will do my best :)
